name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.1.1
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Build LimboFilter
        run: ./gradlew build
      - name: Upload LimboFilter
        uses: actions/upload-artifact@v3.0.0
        with:
          name: LimboFilter Built On ${{ matrix.java }} JDK
          path: "build/libs/limbofilter*.jar"
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        if: ${{ github.event_name == 'push' }}
        with:
          delete_release: true
          tag_name: dev-build-jdk-${{ matrix.java }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release the build
        if: ${{ github.event_name == 'push' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/libs/limbofilter*.jar"
          body: ${{ join(github.event.commits.*.message, '\n') }}
          prerelease: true
          name: JDK ${{ matrix.java }} Dev-build
          tag: dev-build-jdk-${{ matrix.java }}
